### ISSUE TITLE
Use spec'ed minimal preset SLOTS_PER_EPOCH = 8

### ISSUE THREAD

**Issue by dapplion** [Inphi/eip4844-interop#65]
https://github.com/Inphi/eip4844-interop/blob/cad0dab50901cc1371a683388136fd56654d3bba/shared/chain-config.yml#L8

value should be 8 to match client's baked in minimal preset

**Comment by jimmygchen** [comment]
@dapplion is minimal the default preset for Lodestar? 
The `PRESET_BASE` is currently not defined in the chain-config.yml file, and if I remember correctly Prysm loads the mainnet preset as default.

I'm trying to get Lighthouse to run with this config (without a `PRESET_BASE` defined) but it doesn't allow it, so I think we may need to be explicit on defining this.

**Comment by dapplion** [comment]
> @dapplion is minimal the default preset for Lodestar?

Default preset is mainnet, but we support minimal without any code modifications. That's gonna be the case for most CLs, so using the stardard minimal preset will make interop much easier. If you need faster chains, just pick a short SECONDS_PER_SLOT

**Comment by jimmygchen** [comment]
Thanks @dapplion !

There's currently no `PRESET_BASE` specified in the [chain-config.yaml](https://github.com/Inphi/eip4844-interop/blob/cad0dab50901cc1371a683388136fd56654d3bba/shared/chain-config.yml#L8) file, so I guess we're using the mainnet preset? @Inphi and I ran into [some issues](https://github.com/Inphi/eip4844-interop/pull/47#issuecomment-1314693722) getting Prysm to work with minimal preset, but would be great to switch over to minimal once we have it resolved. 

I'm just trying to figure out whether we need to create a new preset for Lighthouse to interop, because the current chain config overrides the `SLOTS_PER_EPOCH` in the mainnet preset, and overriding preset config is not supported in Lighthouse due to [this issue](https://github.com/sigp/lighthouse/issues/3033). So it would be easier if we switch over to minimal and keep `SLOTS_PER_EPOCH` to be 8 as you suggested.

**Comment by jimmygchen** [comment]
Apologies, my questions above are probably not relevant to this issue, will bring this discussion elsewhere :)

**Comment by dapplion** [comment]
Currently uses mainnet preset. No more cursed SLOTS_PER_EPOCH =D

https://github.com/Inphi/eip4844-interop/blob/013741e501abcef636361c9c76c4ef6dbe13b95c/shared/chain-config.yml#L8
